#!/usr/bin/env php
<?php

require_once 'vendor/autoload.php';

if ($argc != 3) {
  printf('Invalid parameter count!' . PHP_EOL . PHP_EOL);
  printf('Usage: ini-diff template ini' . PHP_EOL);
  exit(-1);
}

try {
  $iniDiff = new \IniDiff\IniDiff;
  $iniDiff->setTemplateFile($argv[1]);
  $iniDiff->setIniFile($argv[2]);
  $iniDiff->diff();
} catch (\IniDiff\IniDiffException $ide) {
  echo $ide->getMessage();
  exit(-1);
}

